language: python
python:
- "3.5.0"
# command to install dependencies
install:
- pip install -U pip setuptools
- pip install -r requirements.txt
- pip install pytest
- pip install pytest-cov
- pip install coveralls
# command to run tests
script:
- pytest --cov=.
- coverage
- coveralls
after_success:
- coveralls